export const ActionType = {
    SET_POSTS:"SET_POSTS",
    REMOVE_POSTS:"REMOVE_POSTS",
    SET_VIDEOS:"SET_VIDEOS",
    REMOVE_VIDEOS:"REMOVE_VIDEOS",
    SET_TWEETS:"SET_TWEETS",
    REMOVE_TWEETS:"REMOVE_TWEETS",
    SET_USER:"SET_USER"
}